# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: RFF CI

on:
  push:
    branches: [ dev ]

jobs:
  env:
    CI: true
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: yarn install
    - name: run_tests
      run: yarn ci
    - name: push_coverage
      uses: codecov/codecov-action@v1
      if: always()
      with:
        token: ${{secrets.CODECOV_TOKEN}}
  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: needs.test.run_tests
    steps:
    - uses: actions/checkout@v2
    - run: yarn install
    - name: build
      run: yarn build
    - name: deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: build
    
